### ISSUE TITLE
[Feature] Entity 클래스 생성

### ISSUE THREAD

**Issue by yujung7768903** [UNITCookies/Backend-Cookies#10]
## 💡 Issue

데이터베이스 테이블별로 클래스 생성

## 📝  todo

- [ ] member 클래스 생성
- [ ] letter 클래스 생성
- [ ] read_letter 클래스 생성
